### ISSUE TITLE
check_events_consistent does not return a value

### ISSUE THREAD

**Issue by rdno** [wjlei1990/pypaw#14]
Hi Wenjie,

In [window_weights.py:L136](https://github.com/wjlei1990/pypaw/blob/master/pypaw/window_weights.py#L136-L139) you check for event consistency but the function in pytomo3d does not return a value. Thus, if condition throws an error because `None` has no length. In the recent update of pytomo3d, you check the same condition in the function itself ([link](https://github.com/wjlei1990/pytomo3d/blob/master/pytomo3d/adjoint/sum_adjoint.py#L62-L64)). The check probably is not needed here anymore :)

**Comment by wjlei1990** [comment]
Good catch. Sorry for the late response because of Thanksgiving :)
