### ISSUE TITLE
Parallel makedirs cause error

### ISSUE THREAD

**Issue by rdno** [wjlei1990/pypaw#16]
Hi, 

At [sum_adjoint.py#L76](https://github.com/wjlei1990/pypaw/blob/master/pypaw/sum_adjoint.py#L76-L81l), there is a check for existence of a folder. However, sometimes more than one parallel processes cannot find the folder and try to create it.  This leads slower ones to fail because the other one already created the folder. It also applies to the remove call below.

It seems that pyasdf solves this issue by checking for existence only in rank=0 then broadcasting the result.
[asdf_data_set.py#L1717-L1725](https://github.com/SeismicData/pyasdf/blob/master/pyasdf/asdf_data_set.py#L1717-L1725)

**Comment by wjlei1990** [comment]
Hi Ridvan,

By `Sometimes more than one parallel processes cannot find the folder and try to create it`, do you run the sum in parallel, for example, sum to one adjoint file using parallel? However, the `sum_adjoint.py` are supposed to run only one on process, which means it should run in serial.

If you mean you run lot of sum jobs at the same time, you can create the directory first before launch many jobs.

Does it answer your question?

**Comment by rdno** [comment]
> However, the sum_adjoint.py are supposed to run only one on process, which means it should run in serial.

OK. I did not noticed that it was supposed to be serial. I was running with mpirun. Is there a reason for not being able to run parallel?

**Comment by wjlei1990** [comment]
the adjoint source is stored on `ds.auxililary_data.AdjointSource`. In pyasdf, there is no method supporting the parallel processing the such thing.

Also, I think because summing of the adjoint source is not so time-consuming, so it is not that urgent to add the parallel capability.

**Comment by rdno** [comment]
Ok. Thank you for answering.
