### ISSUE TITLE
Co-exist of R/T/Z and E/N/Z components in final ASDF adjoint sources

### ISSUE THREAD

**Issue by chukren** [wjlei1990/pypaw#5]
Will setting these two parameters to "True" cause the issue?
sum_over_comp_flag: False
add_missing_comp_flag: False

P.S. 
pytomo3D update:  Fri Mar 25 14:27:43 2016 -0400
pypaw update: Sun Mar 27 11:54:21 2016 -0400

**Comment by wjlei1990** [comment]
sum_over_comp_flag should set to be false because we don't have ways to deal with multiple instruments.

If you set rotate to be true, add_missing_comp_flag can be true or false since rotate will automatically implement adding missing components.

**Comment by chukren** [comment]
I think that's the reason, I changed one parfile but forgot update the other. Thanks.

**Comment by wjlei1990** [comment]
But I will still regard this as a issue. I will fix it later.

**Comment by wjlei1990** [comment]
I didn't see this effect even I turned on the "sum_over_comp_flag"...

You may show me you results tomorrow so we can make sure...

**Comment by wjlei1990** [comment]
Hi Youyi,

I think you may not update to the newest version of pypaw. I did another test and it looks fine.
